-- 코드를 입력하세요
 SELECT P.PRODUCT_CODE, SUM(os.SALES_AMOUNT * p.PRICE)  AS SALES
 FROM PRODUCT p JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, P.PRODUCT_CODE